using System.Collections.Immutable;
using GitRunnerManager.Core.Localization;
using GitRunnerManager.Core.Models;

namespace GitRunnerManager.Core.Services;

public class LocalizationService : ILocalizationService
{
    private static readonly ImmutableDictionary<string, string> _english = ImmutableDictionary<string, string>.Empty
        .Add(LocalizationKeys.AppName, "Git runner manager")
        .Add(LocalizationKeys.AppInitializingTitle, "Starting Git runner manager")
        .Add(LocalizationKeys.AppInitializingDescription, "Runner monitoring is starting in the background.")
        .Add(LocalizationKeys.StatusRunnerTitle, "Runner")
        .Add(LocalizationKeys.StatusActivityTitle, "Activity")
        .Add(LocalizationKeys.StatusNetworkTitle, "Network")
        .Add(LocalizationKeys.StatusModeTitle, "Mode")
        .Add(LocalizationKeys.StatusLaunchAtLoginTitle, "Launch at login")
        .Add(LocalizationKeys.ButtonManualStart, "Start manually")
        .Add(LocalizationKeys.ButtonManualStop, "Stop manually")
        .Add(LocalizationKeys.ButtonAutomaticMode, "Automatic mode")
        .Add(LocalizationKeys.ButtonRefresh, "Refresh")
        .Add(LocalizationKeys.ButtonStart, "Start")
        .Add(LocalizationKeys.ButtonStop, "Stop")
        .Add(LocalizationKeys.ButtonRestart, "Restart")
        .Add(LocalizationKeys.ButtonStartAll, "Start all")
        .Add(LocalizationKeys.ButtonStopAll, "Stop all")
        .Add(LocalizationKeys.ButtonRefreshAll, "Refresh all")
        .Add(LocalizationKeys.ButtonAddRunner, "Add runner")
        .Add(LocalizationKeys.ButtonImportRunnerFolder, "Import existing runner folder")
        .Add(LocalizationKeys.ButtonRemoveRunner, "Remove runner")
        .Add(LocalizationKeys.ButtonRemoveProfile, "Remove profile")
        .Add(LocalizationKeys.ButtonCancel, "Cancel")
        .Add(LocalizationKeys.ButtonUpdateRunner, "Update runner")
        .Add(LocalizationKeys.ButtonUpdateAllRunners, "Update all runners")
        .Add(LocalizationKeys.ButtonRefreshStatus, "Refresh status")
        .Add(LocalizationKeys.ButtonOpenFolder, "Open folder")
        .Add(LocalizationKeys.ButtonViewLogs, "View logs")
        .Add(LocalizationKeys.ToggleLaunchAtLogin, "Launch automatically at login")
        .Add(LocalizationKeys.ButtonOpenLoginItemsSettings, "Open Login Items settings")
        .Add(LocalizationKeys.ButtonOpenRunnerDirectory, "Open runner folder")
        .Add(LocalizationKeys.ButtonChooseRunnerDirectory, "Choose folder")
        .Add(LocalizationKeys.ButtonOpenUpdateWindow, "Check for updates")
        .Add(LocalizationKeys.ButtonOpenAboutWindow, "About and links")
        .Add(LocalizationKeys.ButtonOpenSettingsWindow, "Settings...")
        .Add(LocalizationKeys.ButtonOpenActionsDashboard, "Actions...")
        .Add(LocalizationKeys.SettingsWindowTitle, "Settings")
        .Add(LocalizationKeys.SettingsGeneralTitle, "General")
        .Add(LocalizationKeys.SettingsRunnerTitle, "Runner")
        .Add(LocalizationKeys.SettingsRunnersTitle, "Runners")
        .Add(LocalizationKeys.SettingsGitHubAccountsTitle, "GitHub Accounts")
        .Add(LocalizationKeys.SettingsUpdatesTitle, "Updates")
        .Add(LocalizationKeys.SettingsNetworkTitle, "Network")
        .Add(LocalizationKeys.SettingsAdvancedTitle, "Advanced")
        .Add(LocalizationKeys.SettingsDeveloperTitle, "Developer")
        .Add(LocalizationKeys.SettingsAboutTitle, "About")
        .Add(LocalizationKeys.SettingsLanguageTitle, "Language")
        .Add(LocalizationKeys.LanguageSystemDefault, "System default")
        .Add(LocalizationKeys.LanguageHungarian, "Hungarian")
        .Add(LocalizationKeys.LanguageEnglish, "English")
        .Add(LocalizationKeys.SettingsLanguageRestartHint, "Language changes are saved immediately. Some text may update after restarting the app.")
        .Add(LocalizationKeys.SettingsRunnerFolderTitle, "Runner folder")
        .Add(LocalizationKeys.SettingsAutomaticUpdateCheckTitle, "Check for updates automatically")
        .Add(LocalizationKeys.SettingsUpdateChannelTitle, "Update channel")
        .Add(LocalizationKeys.UpdateChannelStable, "Stable")
        .Add(LocalizationKeys.UpdateChannelPreview, "Developer / Preview")
        .Add(LocalizationKeys.SettingsNetworkStateTitle, "Current network")
        .Add(LocalizationKeys.SettingsNetworkPolicyTitle, "Network policy")
        .Add(LocalizationKeys.SettingsNetworkOverrideTitle, "Manual override")
        .Add(LocalizationKeys.SettingsNetworkExplanation, "Automatic mode runs the runner on unmetered connections and stops it when the network is offline or metered.")
        .Add(LocalizationKeys.SettingsNetworkDecisionExplanation, "Unmetered -> run\nExpensive/offline -> stop\nUnknown -> keep current state")
        .Add(LocalizationKeys.SettingsAdvancedRunnerProcessTitle, "Runner process")
        .Add(LocalizationKeys.SettingsAdvancedCPU, "Total runner CPU")
        .Add(LocalizationKeys.SettingsAdvancedMemory, "Total runner memory")
        .Add(LocalizationKeys.SettingsAdvancedProcesses, "Processes")
        .Add(LocalizationKeys.SettingsAdvancedWarning, "Diagnostics")
        .Add(LocalizationKeys.SettingsAdvancedJobActive, "Job active")
        .Add(LocalizationKeys.SettingsAdvancedLastRefresh, "Last refresh")
        .Add(LocalizationKeys.SettingsDeveloperLogDirectoryTitle, "Log folder")
        .Add(LocalizationKeys.SettingsDeveloperLogDirectoryDescription, "Diagnostic logs for the app are written to this folder.")
        .Add(LocalizationKeys.SettingsAboutAppNameTitle, "App name")
        .Add(LocalizationKeys.SettingsAboutLicenseTitle, "License")
        .Add(LocalizationKeys.SettingsAboutLicenseValue, "MIT")
        .Add(LocalizationKeys.AdvancedViewTitle, "Advanced view")
        .Add(LocalizationKeys.BooleanYes, "Yes")
        .Add(LocalizationKeys.BooleanNo, "No")
        .Add(LocalizationKeys.AboutWindowTitle, "About Git runner manager")
        .Add(LocalizationKeys.AboutDescription, "Created by Benedek Koncsik. Open the profile pages or the project repository directly from the menu.")
        .Add(LocalizationKeys.ButtonOpenAuthorGitHub, "GitHub profile")
        .Add(LocalizationKeys.ButtonOpenAuthorX, "X profile")
        .Add(LocalizationKeys.ButtonOpenRepository, "Project repository")
        .Add(LocalizationKeys.UpdateWindowTitle, "Software update")
        .Add(LocalizationKeys.UpdateDescription, "Check the latest GitHub release and open the downloaded installer.")
        .Add(LocalizationKeys.UpdateInstalledVersionTitle, "Installed version")
        .Add(LocalizationKeys.UpdateLatestVersionTitle, "Latest version")
        .Add(LocalizationKeys.UpdateStatusTitle, "Status")
        .Add(LocalizationKeys.UpdateUnknownVersion, "Not checked yet")
        .Add(LocalizationKeys.ButtonCheckForUpdates, "Check now")
        .Add(LocalizationKeys.ButtonInstallUpdate, "Download installer")
        .Add(LocalizationKeys.ButtonOpenReleasePage, "Open release page")
        .Add(LocalizationKeys.UpdateIdle, "Ready to check for updates.")
        .Add(LocalizationKeys.UpdateChecking, "Checking GitHub releases...")
        .Add(LocalizationKeys.UpdateUpToDate, "You already have the latest version.")
        .Add(LocalizationKeys.UpdateAvailableFallback, "A newer version is available.")
        .Add(LocalizationKeys.UpdateDownloading, "Downloading the new version...")
        .Add(LocalizationKeys.UpdateInstalling, "Opening the downloaded installer...")
        .Add(LocalizationKeys.UpdateErrorInvalidResponse, "The update server returned an unexpected response.")
        .Add(LocalizationKeys.UpdateErrorNoPublishedRelease, "No published GitHub release is available yet for this repository.")
        .Add(LocalizationKeys.UpdateErrorMissingAsset, "The latest release does not contain a platform app download.")
        .Add(LocalizationKeys.UpdateErrorDownload, "The update package could not be downloaded.")
        .Add(LocalizationKeys.UpdateErrorOpenInstaller, "The downloaded installer could not be opened.")
        .Add(LocalizationKeys.UpdateErrorNoRelease, "There is no downloadable release selected.")
        .Add(LocalizationKeys.ButtonQuit, "Quit")
        .Add(LocalizationKeys.RunnerRunning, "Running")
        .Add(LocalizationKeys.RunnerStopped, "Stopped")
        .Add(LocalizationKeys.RunnerStatusBusy, "Busy")
        .Add(LocalizationKeys.RunnerStatusWaiting, "Waiting")
        .Add(LocalizationKeys.RunnerStatusError, "Error")
        .Add(LocalizationKeys.RunnerStatusNoRunners, "No runners configured")
        .Add(LocalizationKeys.RunnerNoRunnersConfigured, "No runners configured yet.")
        .Add(LocalizationKeys.RunnerAddOrImportHint, "Add or import a runner to manage it here.")
        .Add(LocalizationKeys.RunnerUpdateIdle, "Runner updates are idle.")
        .Add(LocalizationKeys.RunnerUpdateVersionSummary, "{0}: installed {1}, latest {2}.")
        .Add(LocalizationKeys.RunnerRemoveTitle, "Remove runner")
        .Add(LocalizationKeys.RunnerRemoveConfirmation, "Remove this runner profile from the app? The runner folder and GitHub configuration files will not be deleted.")
        .Add(LocalizationKeys.RunnerStatusTitle, "Status")
        .Add(LocalizationKeys.RunnerResourcesTitle, "Resources")
        .Add(LocalizationKeys.RunnerDisplayNameTitle, "Display name")
        .Add(LocalizationKeys.RunnerDirectoryTitle, "Runner directory")
        .Add(LocalizationKeys.RunnerOwnerOrOrgTitle, "GitHub owner or org")
        .Add(LocalizationKeys.RunnerRepositoryNameTitle, "Repository name")
        .Add(LocalizationKeys.RunnerLabelsTitle, "Labels")
        .Add(LocalizationKeys.RunnerOrganizationToggle, "Organization runner")
        .Add(LocalizationKeys.RunnerAutoStartToggle, "Auto start")
        .Add(LocalizationKeys.RunnerAutomaticModeToggle, "Automatic mode")
        .Add(LocalizationKeys.RunnerStopOnBatteryToggle, "Stop on battery")
        .Add(LocalizationKeys.RunnerStopOnMeteredNetworkToggle, "Stop on metered network")
        .Add(LocalizationKeys.RunnerEnabledToggle, "Enabled")
        .Add(LocalizationKeys.GitHubAccountsPlaceholder, "GitHub account setup will live here. Runner profiles already capture the owner, organization, and repository fields needed for runner management.")
        .Add(LocalizationKeys.GitHubSetupInstructionsTitle, "GitHub setup")
        .Add(LocalizationKeys.GitHubSetupInstructionsBody, "Create a free OAuth App at https://github.com/settings/developers. Open OAuth Apps, create a new app, fill the fields below, enable Device Flow, register the app, then paste the Client ID here. Repository runners require repository admin access. Organization runners require organization admin access and the admin:org scope.")
        .Add(LocalizationKeys.GitHubOAuthAppValuesTitle, "OAuth App fields")
        .Add(LocalizationKeys.GitHubOAuthApplicationName, "Application name")
        .Add(LocalizationKeys.GitHubOAuthHomepageUrl, "Homepage URL")
        .Add(LocalizationKeys.GitHubOAuthCallbackUrl, "Authorization callback URL")
        .Add(LocalizationKeys.GitHubOAuthDeviceFlow, "Device Flow")
        .Add(LocalizationKeys.GitHubOAuthApplicationNameValue, "Git runner manager")
        .Add(LocalizationKeys.GitHubOAuthHomepageUrlValue, "https://github.com/HunKonTech/GitRunnerManager")
        .Add(LocalizationKeys.GitHubOAuthCallbackUrlValue, "http://localhost")
        .Add(LocalizationKeys.GitHubOAuthDeviceFlowValue, "Enable Device Flow")
        .Add(LocalizationKeys.GitHubOAuthClientIdTitle, "OAuth Client ID")
        .Add(LocalizationKeys.GitHubSignInButton, "Sign in with GitHub")
        .Add(LocalizationKeys.GitHubSignOutButton, "Sign out")
        .Add(LocalizationKeys.GitHubOpenDevicePageButton, "Open GitHub device page")
        .Add(LocalizationKeys.GitHubSignedInAs, "Signed in as {0}")
        .Add(LocalizationKeys.GitHubNotSignedIn, "Not signed in")
        .Add(LocalizationKeys.GitHubDeviceCode, "Device code: {0}")
        .Add(LocalizationKeys.GitHubRunnerSetupTitle, "Create and configure runner")
        .Add(LocalizationKeys.GitHubRunnerScopeTitle, "Runner type")
        .Add(LocalizationKeys.GitHubRunnerScopeRepository, "Repository runner")
        .Add(LocalizationKeys.GitHubRunnerScopeOrganization, "Organization runner")
        .Add(LocalizationKeys.GitHubOwnerOrgField, "Owner or organization")
        .Add(LocalizationKeys.GitHubRepositoryField, "Repository")
        .Add(LocalizationKeys.GitHubRunnerNameField, "Runner name")
        .Add(LocalizationKeys.GitHubRunnerDirectoryField, "Runner directory")
        .Add(LocalizationKeys.GitHubCreateConfigureRunnerButton, "Create and configure runner")
        .Add(LocalizationKeys.GitHubStatusReady, "Ready.")
        .Add(LocalizationKeys.GitHubStatusSigningIn, "Waiting for GitHub authorization...")
        .Add(LocalizationKeys.GitHubStatusConfigured, "Runner configured and added.")
        .Add(LocalizationKeys.GitHubStatusError, "GitHub error: {0}")
        .Add(LocalizationKeys.ActionsDashboardTitle, "GitHub Actions Dashboard")
        .Add(LocalizationKeys.ActionsRunnerSection, "Runner")
        .Add(LocalizationKeys.ActionsWorkflowRunsSection, "Workflow runs")
        .Add(LocalizationKeys.ActionsJobDetailSection, "Jobs")
        .Add(LocalizationKeys.ActionsLastRefresh, "Last refresh")
        .Add(LocalizationKeys.ActionsRunnerGroup, "Runner group")
        .Add(LocalizationKeys.ActionsAllowedRepositories, "Allowed repositories")
        .Add(LocalizationKeys.ActionsRunningOnThisRunner, "Running on this runner")
        .Add(LocalizationKeys.ActionsOpenInBrowser, "Open")
        .Add(LocalizationKeys.ActionsSelectRun, "Jobs")
        .Add(LocalizationKeys.ActionsSelectRunHint, "Select a workflow run to see its jobs.")
        .Add(LocalizationKeys.ActionsNoWorkflowRuns, "No visible workflow runs.")
        .Add(LocalizationKeys.ActionsLoading, "Loading...")
        .Add(LocalizationKeys.ActionsMovedFromSettings, "GitHub sign-in and Actions data are now available from the Actions dashboard.")
        .Add(LocalizationKeys.ActionsOrganizationRunnerGuideTitle, "Organization runner access")
        .Add(LocalizationKeys.ActionsOrganizationRunnerGuideBody, "Organization-level runner details are only visible to GitHub users with organization admin permission. To see runner groups and selected repositories, sign in with an OAuth app that has Device Flow enabled and grants repo plus admin:org access. Without admin permission the dashboard still shows accessible workflow runs, but runner group details are marked as permission required.")
        .Add(LocalizationKeys.ActionsPermissionRequired, "Permission required")
        .Add(LocalizationKeys.ActionsAllOrganizationRepositories, "All repositories in organization")
        .Add(LocalizationKeys.ActionsRunnerAdminPermissionRequired, "Organization runner details require admin permission.")
        .Add(LocalizationKeys.ActionsSignInRequired, "Sign in to GitHub to load Actions data.")
        .Add(LocalizationKeys.ActionsOAuthClientIdRequired, "OAuth Client ID is required.")
        .Add(LocalizationKeys.ActionsSignedIn, "Signed in.")
        .Add(LocalizationKeys.ActionsSignedOut, "Signed out.")
        .Add(LocalizationKeys.ActionsStatusQueued, "Queued")
        .Add(LocalizationKeys.ActionsStatusInProgress, "In progress")
        .Add(LocalizationKeys.ActionsStatusCompleted, "Completed")
        .Add(LocalizationKeys.ActionsStatusWaiting, "Waiting")
        .Add(LocalizationKeys.ActionsStatusRequested, "Requested")
        .Add(LocalizationKeys.ActionsStatusOnline, "Online")
        .Add(LocalizationKeys.ActionsStatusOffline, "Offline")
        .Add(LocalizationKeys.ActionsStatusUnknown, "Unknown")
        .Add(LocalizationKeys.ActionsConclusionSuccess, "Success")
        .Add(LocalizationKeys.ActionsConclusionFailure, "Failure")
        .Add(LocalizationKeys.ActionsConclusionCancelled, "Cancelled")
        .Add(LocalizationKeys.ActionsConclusionSkipped, "Skipped")
        .Add(LocalizationKeys.ActionsConclusionTimedOut, "Timed out")
        .Add(LocalizationKeys.ControlModeAutomatic, "Automatic")
        .Add(LocalizationKeys.ControlModeManual, "Manual")
        .Add(LocalizationKeys.ControlModeForceRunning, "Forced running")
        .Add(LocalizationKeys.ControlModeForceStopped, "Forced stopped")
        .Add(LocalizationKeys.PolicyAutomaticRun, "In automatic mode the runner may run.")
        .Add(LocalizationKeys.PolicyAutomaticExpensive, "In automatic mode the runner stops on a metered connection.")
        .Add(LocalizationKeys.PolicyAutomaticExpensiveIgnored, "In automatic mode the runner may run because metered connection pausing is turned off.")
        .Add(LocalizationKeys.PolicyAutomaticOffline, "In automatic mode the runner stops when there is no internet.")
        .Add(LocalizationKeys.PolicyAutomaticUnknown, "In automatic mode the app is still checking the network.")
        .Add(LocalizationKeys.PolicyForceRunning, "Manual override keeps the runner running regardless of network rules.")
        .Add(LocalizationKeys.PolicyForceStopped, "Manual override keeps the runner stopped.")
        .Add(LocalizationKeys.LaunchAtLoginEnabled, "Enabled")
        .Add(LocalizationKeys.LaunchAtLoginRequiresApproval, "Approval required")
        .Add(LocalizationKeys.LaunchAtLoginDisabled, "Disabled")
        .Add(LocalizationKeys.LaunchAtLoginUnavailable, "Unavailable in this build")
        .Add(LocalizationKeys.LaunchAtLoginUnknown, "Unknown")
        .Add(LocalizationKeys.ActivityWorkingJob, "Working: {0}")
        .Add(LocalizationKeys.ActivityWaitingForJob, "Waiting for jobs")
        .Add(LocalizationKeys.ActivityStopping, "Stopping")
        .Add(LocalizationKeys.ActivityWaitingOrStarting, "Waiting or starting")
        .Add(LocalizationKeys.ActivityRunnerStopped, "The runner is stopped")
        .Add(LocalizationKeys.ActivityUnknown, "Unknown status")
        .Add(LocalizationKeys.NetworkChecking, "Checking network...")
        .Add(LocalizationKeys.NetworkNoInternet, "No internet connection")
        .Add(LocalizationKeys.NetworkMetered, "{0}, metered")
        .Add(LocalizationKeys.NetworkUnmetered, "{0}, unmetered")
        .Add(LocalizationKeys.InterfaceEthernet, "Ethernet")
        .Add(LocalizationKeys.InterfaceWiFi, "Wi-Fi")
        .Add(LocalizationKeys.InterfaceCellular, "Cellular")
        .Add(LocalizationKeys.InterfaceOther, "Other connection")
        .Add(LocalizationKeys.InterfaceGeneric, "Connection")
        .Add(LocalizationKeys.ErrorMissingRunnerScript, "Cannot find the runner startup script: {0}")
        .Add(LocalizationKeys.ErrorLaunchAtLoginUpdate, "Failed to update launch at login: {0}")
        .Add(LocalizationKeys.ErrorRunnerHandling, "Failed to manage the runner: {0}")
        .Add(LocalizationKeys.SettingsStopOnBatteryTitle, "Pause runner on battery")
        .Add(LocalizationKeys.SettingsStopOnBatteryExplanation, "Automatically stop the runner when running on battery power and resume when connected to power.")
        .Add(LocalizationKeys.SettingsStopOnBatteryUnavailable, "Not available on this device")
        .Add(LocalizationKeys.SettingsStopOnMeteredNetworkTitle, "Pause runner on metered connections")
        .Add(LocalizationKeys.SettingsStopOnMeteredNetworkExplanation, "Automatically stop the runner when the active internet connection is metered.");

    private static readonly ImmutableDictionary<string, string> _hungarian = ImmutableDictionary<string, string>.Empty
        .Add(LocalizationKeys.AppName, "Git runner manager")
        .Add(LocalizationKeys.AppInitializingTitle, "Git runner manager indítása")
        .Add(LocalizationKeys.AppInitializingDescription, "A runner figyelése a háttérben indul.")
        .Add(LocalizationKeys.StatusRunnerTitle, "Runner")
        .Add(LocalizationKeys.StatusActivityTitle, "Munka")
        .Add(LocalizationKeys.StatusNetworkTitle, "Hálózat")
        .Add(LocalizationKeys.StatusModeTitle, "Mód")
        .Add(LocalizationKeys.StatusLaunchAtLoginTitle, "Induláskor")
        .Add(LocalizationKeys.ButtonManualStart, "Indítás kézzel")
        .Add(LocalizationKeys.ButtonManualStop, "Leállítás kézzel")
        .Add(LocalizationKeys.ButtonAutomaticMode, "Automatikus mód")
        .Add(LocalizationKeys.ButtonRefresh, "Frissítés")
        .Add(LocalizationKeys.ButtonStart, "Indítás")
        .Add(LocalizationKeys.ButtonStop, "Leállítás")
        .Add(LocalizationKeys.ButtonRestart, "Újraindítás")
        .Add(LocalizationKeys.ButtonStartAll, "Összes indítása")
        .Add(LocalizationKeys.ButtonStopAll, "Összes leállítása")
        .Add(LocalizationKeys.ButtonRefreshAll, "Összes frissítése")
        .Add(LocalizationKeys.ButtonAddRunner, "Runner hozzáadása")
        .Add(LocalizationKeys.ButtonImportRunnerFolder, "Meglévő runner mappa importálása")
        .Add(LocalizationKeys.ButtonRemoveRunner, "Runner eltávolítása")
        .Add(LocalizationKeys.ButtonRemoveProfile, "Profil eltávolítása")
        .Add(LocalizationKeys.ButtonCancel, "Mégse")
        .Add(LocalizationKeys.ButtonUpdateRunner, "Runner frissítése")
        .Add(LocalizationKeys.ButtonUpdateAllRunners, "Összes runner frissítése")
        .Add(LocalizationKeys.ButtonRefreshStatus, "Állapot frissítése")
        .Add(LocalizationKeys.ButtonOpenFolder, "Mappa megnyitása")
        .Add(LocalizationKeys.ButtonViewLogs, "Naplók megtekintése")
        .Add(LocalizationKeys.ToggleLaunchAtLogin, "Induljon automatikusan bejelentkezéskor")
        .Add(LocalizationKeys.ButtonOpenLoginItemsSettings, "Login Items beállítások megnyitása")
        .Add(LocalizationKeys.ButtonOpenRunnerDirectory, "Runner mappa megnyitása")
        .Add(LocalizationKeys.ButtonChooseRunnerDirectory, "Mappa kiválasztása")
        .Add(LocalizationKeys.ButtonOpenUpdateWindow, "Frissítések keresése")
        .Add(LocalizationKeys.ButtonOpenAboutWindow, "Névjegy és linkek")
        .Add(LocalizationKeys.ButtonOpenSettingsWindow, "Beállítások...")
        .Add(LocalizationKeys.ButtonOpenActionsDashboard, "Actions...")
        .Add(LocalizationKeys.SettingsWindowTitle, "Beállítások")
        .Add(LocalizationKeys.SettingsGeneralTitle, "Általános")
        .Add(LocalizationKeys.SettingsRunnerTitle, "Runner")
        .Add(LocalizationKeys.SettingsRunnersTitle, "Runnerek")
        .Add(LocalizationKeys.SettingsGitHubAccountsTitle, "GitHub fiókok")
        .Add(LocalizationKeys.SettingsUpdatesTitle, "Frissítések")
        .Add(LocalizationKeys.SettingsNetworkTitle, "Hálózat")
        .Add(LocalizationKeys.SettingsAdvancedTitle, "Haladó")
        .Add(LocalizationKeys.SettingsDeveloperTitle, "Fejlesztői")
        .Add(LocalizationKeys.SettingsAboutTitle, "Névjegy")
        .Add(LocalizationKeys.SettingsLanguageTitle, "Nyelv")
        .Add(LocalizationKeys.LanguageSystemDefault, "Rendszer alapértelmezése")
        .Add(LocalizationKeys.LanguageHungarian, "Magyar")
        .Add(LocalizationKeys.LanguageEnglish, "Angol")
        .Add(LocalizationKeys.SettingsLanguageRestartHint, "A nyelvválasztást az app azonnal menti. Néhány szöveg csak az app újraindítása után frissülhet.")
        .Add(LocalizationKeys.SettingsRunnerFolderTitle, "Runner mappa")
        .Add(LocalizationKeys.SettingsAutomaticUpdateCheckTitle, "Frissítések automatikus keresése")
        .Add(LocalizationKeys.SettingsUpdateChannelTitle, "Frissítési csatorna")
        .Add(LocalizationKeys.UpdateChannelStable, "Stabil")
        .Add(LocalizationKeys.UpdateChannelPreview, "Fejlesztői / előnézeti")
        .Add(LocalizationKeys.SettingsNetworkStateTitle, "Aktuális hálózat")
        .Add(LocalizationKeys.SettingsNetworkPolicyTitle, "Hálózati szabály")
        .Add(LocalizationKeys.SettingsNetworkOverrideTitle, "Kézi felülbírálás")
        .Add(LocalizationKeys.SettingsNetworkExplanation, "Automatikus módban a runner nem forgalomkorlátos kapcsolaton futhat, offline vagy forgalomkorlátos hálózaton pedig leáll.")
        .Add(LocalizationKeys.SettingsNetworkDecisionExplanation, "Nem forgalomkorlátos -> futtatás\nForgalomkorlátos/offline -> leállítás\nIsmeretlen -> aktuális állapot megtartása")
        .Add(LocalizationKeys.SettingsAdvancedRunnerProcessTitle, "Runner folyamat")
        .Add(LocalizationKeys.SettingsAdvancedCPU, "Teljes runner CPU")
        .Add(LocalizationKeys.SettingsAdvancedMemory, "Teljes runner memória")
        .Add(LocalizationKeys.SettingsAdvancedProcesses, "Folyamatok")
        .Add(LocalizationKeys.SettingsAdvancedWarning, "Diagnosztika")
        .Add(LocalizationKeys.SettingsAdvancedJobActive, "Aktív job")
        .Add(LocalizationKeys.SettingsAdvancedLastRefresh, "Utolsó frissítés")
        .Add(LocalizationKeys.SettingsDeveloperLogDirectoryTitle, "Log mappa")
        .Add(LocalizationKeys.SettingsDeveloperLogDirectoryDescription, "Az app diagnosztikai naplói ebbe a mappába kerülnek.")
        .Add(LocalizationKeys.SettingsAboutAppNameTitle, "App neve")
        .Add(LocalizationKeys.SettingsAboutLicenseTitle, "Licenc")
        .Add(LocalizationKeys.SettingsAboutLicenseValue, "MIT")
        .Add(LocalizationKeys.AdvancedViewTitle, "Haladó nézet")
        .Add(LocalizationKeys.BooleanYes, "Igen")
        .Add(LocalizationKeys.BooleanNo, "Nem")
        .Add(LocalizationKeys.AboutWindowTitle, "Git runner manager névjegy")
        .Add(LocalizationKeys.AboutDescription, "Készítette Benedek Koncsik. Innen közvetlenül megnyithatod a profiloldalakat és a projekt repositoryját.")
        .Add(LocalizationKeys.ButtonOpenAuthorGitHub, "GitHub profil")
        .Add(LocalizationKeys.ButtonOpenAuthorX, "X profil")
        .Add(LocalizationKeys.ButtonOpenRepository, "Projekt repository")
        .Add(LocalizationKeys.UpdateWindowTitle, "Szoftverfrissítés")
        .Add(LocalizationKeys.UpdateDescription, "Ellenőrzi a legfrissebb GitHub release-t, letölti és megnyitja a telepítőt.")
        .Add(LocalizationKeys.UpdateInstalledVersionTitle, "Telepített verzió")
        .Add(LocalizationKeys.UpdateLatestVersionTitle, "Legfrissebb verzió")
        .Add(LocalizationKeys.UpdateStatusTitle, "Állapot")
        .Add(LocalizationKeys.UpdateUnknownVersion, "Még nincs ellenőrizve")
        .Add(LocalizationKeys.ButtonCheckForUpdates, "Ellenőrzés")
        .Add(LocalizationKeys.ButtonInstallUpdate, "Telepítő letöltése")
        .Add(LocalizationKeys.ButtonOpenReleasePage, "Release oldal megnyitása")
        .Add(LocalizationKeys.UpdateIdle, "Készen áll a frissítések ellenőrzésére.")
        .Add(LocalizationKeys.UpdateChecking, "GitHub release-ek ellenőrzése...")
        .Add(LocalizationKeys.UpdateUpToDate, "Már a legfrissebb verzió van telepítve.")
        .Add(LocalizationKeys.UpdateAvailableFallback, "Elérhető egy újabb verzió.")
        .Add(LocalizationKeys.UpdateDownloading, "Az új verzió letöltése folyamatban...")
        .Add(LocalizationKeys.UpdateInstalling, "A letöltött telepítő megnyitása...")
        .Add(LocalizationKeys.UpdateErrorInvalidResponse, "A frissítési kiszolgáló váratlan választ adott.")
        .Add(LocalizationKeys.UpdateErrorNoPublishedRelease, "Ehhez a repositoryhoz még nincs közzétett GitHub release.")
        .Add(LocalizationKeys.UpdateErrorMissingAsset, "A legfrissebb release nem tartalmaz letölthető alkalmazást.")
        .Add(LocalizationKeys.UpdateErrorDownload, "Nem sikerült letölteni a frissítő csomagot.")
        .Add(LocalizationKeys.UpdateErrorOpenInstaller, "Nem sikerült megnyitni a letöltött telepítőt.")
        .Add(LocalizationKeys.UpdateErrorNoRelease, "Nincs kiválasztott letölthető release.")
        .Add(LocalizationKeys.ButtonQuit, "Kilépés")
        .Add(LocalizationKeys.RunnerRunning, "Fut")
        .Add(LocalizationKeys.RunnerStopped, "Leállítva")
        .Add(LocalizationKeys.RunnerStatusBusy, "Dolgozik")
        .Add(LocalizationKeys.RunnerStatusWaiting, "Várakozik")
        .Add(LocalizationKeys.RunnerStatusError, "Hiba")
        .Add(LocalizationKeys.RunnerStatusNoRunners, "Nincs beállított runner")
        .Add(LocalizationKeys.RunnerNoRunnersConfigured, "Még nincs beállított runner.")
        .Add(LocalizationKeys.RunnerAddOrImportHint, "Adj hozzá vagy importálj egy runnert, hogy itt kezelhesd.")
        .Add(LocalizationKeys.RunnerUpdateIdle, "A runner frissítések tétlenek.")
        .Add(LocalizationKeys.RunnerUpdateVersionSummary, "{0}: telepített {1}, legfrissebb {2}.")
        .Add(LocalizationKeys.RunnerRemoveTitle, "Runner eltávolítása")
        .Add(LocalizationKeys.RunnerRemoveConfirmation, "Eltávolítod ezt a runner profilt az appból? A runner mappa és a GitHub konfigurációs fájlok nem törlődnek.")
        .Add(LocalizationKeys.RunnerStatusTitle, "Állapot")
        .Add(LocalizationKeys.RunnerResourcesTitle, "Erőforrások")
        .Add(LocalizationKeys.RunnerDisplayNameTitle, "Megjelenített név")
        .Add(LocalizationKeys.RunnerDirectoryTitle, "Runner mappa")
        .Add(LocalizationKeys.RunnerOwnerOrOrgTitle, "GitHub tulajdonos vagy szervezet")
        .Add(LocalizationKeys.RunnerRepositoryNameTitle, "Repository neve")
        .Add(LocalizationKeys.RunnerLabelsTitle, "Címkék")
        .Add(LocalizationKeys.RunnerOrganizationToggle, "Szervezeti runner")
        .Add(LocalizationKeys.RunnerAutoStartToggle, "Automatikus indítás")
        .Add(LocalizationKeys.RunnerAutomaticModeToggle, "Automatikus mód")
        .Add(LocalizationKeys.RunnerStopOnBatteryToggle, "Leállítás akkumulátoron")
        .Add(LocalizationKeys.RunnerStopOnMeteredNetworkToggle, "Leállítás forgalomkorlátos hálózaton")
        .Add(LocalizationKeys.RunnerEnabledToggle, "Engedélyezve")
        .Add(LocalizationKeys.GitHubAccountsPlaceholder, "A GitHub fiókok beállításai ide kerülnek majd. A runner profilok már tartalmazzák a runner kezeléséhez szükséges tulajdonos, szervezet és repository mezőket.")
        .Add(LocalizationKeys.GitHubSetupInstructionsTitle, "GitHub beállítás")
        .Add(LocalizationKeys.GitHubSetupInstructionsBody, "Hozz létre ingyenes OAuth Appot itt: https://github.com/settings/developers. Nyisd meg az OAuth Apps részt, hozz létre új appot, töltsd ki az alábbi mezőket, kapcsold be a Device Flow-t, regisztráld az appot, majd illeszd be ide a Client ID-t. Repository runnerhez repository admin jog kell. Organization runnerhez organization admin jog és admin:org scope kell.")
        .Add(LocalizationKeys.GitHubOAuthAppValuesTitle, "OAuth App mezők")
        .Add(LocalizationKeys.GitHubOAuthApplicationName, "Application name")
        .Add(LocalizationKeys.GitHubOAuthHomepageUrl, "Homepage URL")
        .Add(LocalizationKeys.GitHubOAuthCallbackUrl, "Authorization callback URL")
        .Add(LocalizationKeys.GitHubOAuthDeviceFlow, "Device Flow")
        .Add(LocalizationKeys.GitHubOAuthApplicationNameValue, "Git runner manager")
        .Add(LocalizationKeys.GitHubOAuthHomepageUrlValue, "https://github.com/HunKonTech/GitRunnerManager")
        .Add(LocalizationKeys.GitHubOAuthCallbackUrlValue, "http://localhost")
        .Add(LocalizationKeys.GitHubOAuthDeviceFlowValue, "Enable Device Flow bekapcsolva")
        .Add(LocalizationKeys.GitHubOAuthClientIdTitle, "OAuth Client ID")
        .Add(LocalizationKeys.GitHubSignInButton, "Bejelentkezés GitHubbal")
        .Add(LocalizationKeys.GitHubSignOutButton, "Kijelentkezés")
        .Add(LocalizationKeys.GitHubOpenDevicePageButton, "GitHub device oldal megnyitása")
        .Add(LocalizationKeys.GitHubSignedInAs, "Bejelentkezve: {0}")
        .Add(LocalizationKeys.GitHubNotSignedIn, "Nincs bejelentkezve")
        .Add(LocalizationKeys.GitHubDeviceCode, "Device kód: {0}")
        .Add(LocalizationKeys.GitHubRunnerSetupTitle, "Runner létrehozása és konfigurálása")
        .Add(LocalizationKeys.GitHubRunnerScopeTitle, "Runner típusa")
        .Add(LocalizationKeys.GitHubRunnerScopeRepository, "Repository runner")
        .Add(LocalizationKeys.GitHubRunnerScopeOrganization, "Szervezeti runner")
        .Add(LocalizationKeys.GitHubOwnerOrgField, "Tulajdonos vagy szervezet")
        .Add(LocalizationKeys.GitHubRepositoryField, "Repository")
        .Add(LocalizationKeys.GitHubRunnerNameField, "Runner neve")
        .Add(LocalizationKeys.GitHubRunnerDirectoryField, "Runner mappa")
        .Add(LocalizationKeys.GitHubCreateConfigureRunnerButton, "Runner létrehozása és konfigurálása")
        .Add(LocalizationKeys.GitHubStatusReady, "Készen áll.")
        .Add(LocalizationKeys.GitHubStatusSigningIn, "Várakozás a GitHub jóváhagyásra...")
        .Add(LocalizationKeys.GitHubStatusConfigured, "Runner konfigurálva és hozzáadva.")
        .Add(LocalizationKeys.GitHubStatusError, "GitHub hiba: {0}")
        .Add(LocalizationKeys.ActionsDashboardTitle, "GitHub Actions irányítópult")
        .Add(LocalizationKeys.ActionsRunnerSection, "Runner")
        .Add(LocalizationKeys.ActionsWorkflowRunsSection, "Workflow futások")
        .Add(LocalizationKeys.ActionsJobDetailSection, "Jobok")
        .Add(LocalizationKeys.ActionsLastRefresh, "Utolsó frissítés")
        .Add(LocalizationKeys.ActionsRunnerGroup, "Runner csoport")
        .Add(LocalizationKeys.ActionsAllowedRepositories, "Engedélyezett repositoryk")
        .Add(LocalizationKeys.ActionsRunningOnThisRunner, "Ezen a runneren fut")
        .Add(LocalizationKeys.ActionsOpenInBrowser, "Megnyitás")
        .Add(LocalizationKeys.ActionsSelectRun, "Jobok")
        .Add(LocalizationKeys.ActionsSelectRunHint, "Válassz egy workflow futást a jobok megtekintéséhez.")
        .Add(LocalizationKeys.ActionsNoWorkflowRuns, "Nincs látható workflow futás.")
        .Add(LocalizationKeys.ActionsLoading, "Betöltés...")
        .Add(LocalizationKeys.ActionsMovedFromSettings, "A GitHub bejelentkezés és az Actions adatok mostantól az Actions irányítópulton érhetők el.")
        .Add(LocalizationKeys.ActionsOrganizationRunnerGuideTitle, "Szervezeti runner hozzáférés")
        .Add(LocalizationKeys.ActionsOrganizationRunnerGuideBody, "A szervezeti szintű runner részletei csak organization admin jogosultságú GitHub felhasználóknak láthatók. A runner csoportok és a kiválasztott repositoryk megjelenítéséhez olyan OAuth appal jelentkezz be, amelynél engedélyezve van a Device Flow, és repo valamint admin:org hozzáférést kér. Admin jogosultság nélkül az irányítópult továbbra is mutatja az elérhető workflow futásokat, de a runner csoport részleteinél jogosultság szükséges üzenet jelenik meg.")
        .Add(LocalizationKeys.ActionsPermissionRequired, "Jogosultság szükséges")
        .Add(LocalizationKeys.ActionsAllOrganizationRepositories, "A szervezet összes repositoryja")
        .Add(LocalizationKeys.ActionsRunnerAdminPermissionRequired, "A szervezeti runner részleteihez admin jogosultság szükséges.")
        .Add(LocalizationKeys.ActionsSignInRequired, "Jelentkezz be GitHubbal az Actions adatok betöltéséhez.")
        .Add(LocalizationKeys.ActionsOAuthClientIdRequired, "OAuth Client ID szükséges.")
        .Add(LocalizationKeys.ActionsSignedIn, "Bejelentkezve.")
        .Add(LocalizationKeys.ActionsSignedOut, "Kijelentkezve.")
        .Add(LocalizationKeys.ActionsStatusQueued, "Sorban áll")
        .Add(LocalizationKeys.ActionsStatusInProgress, "Folyamatban")
        .Add(LocalizationKeys.ActionsStatusCompleted, "Befejezve")
        .Add(LocalizationKeys.ActionsStatusWaiting, "Várakozik")
        .Add(LocalizationKeys.ActionsStatusRequested, "Kérve")
        .Add(LocalizationKeys.ActionsStatusOnline, "Online")
        .Add(LocalizationKeys.ActionsStatusOffline, "Offline")
        .Add(LocalizationKeys.ActionsStatusUnknown, "Ismeretlen")
        .Add(LocalizationKeys.ActionsConclusionSuccess, "Sikeres")
        .Add(LocalizationKeys.ActionsConclusionFailure, "Sikertelen")
        .Add(LocalizationKeys.ActionsConclusionCancelled, "Megszakítva")
        .Add(LocalizationKeys.ActionsConclusionSkipped, "Kihagyva")
        .Add(LocalizationKeys.ActionsConclusionTimedOut, "Időtúllépés")
        .Add(LocalizationKeys.ControlModeAutomatic, "Automatikus")
        .Add(LocalizationKeys.ControlModeManual, "Kézi")
        .Add(LocalizationKeys.ControlModeForceRunning, "Kézileg fut")
        .Add(LocalizationKeys.ControlModeForceStopped, "Kézileg leállítva")
        .Add(LocalizationKeys.PolicyAutomaticRun, "Automatikus módban a runner futhat.")
        .Add(LocalizationKeys.PolicyAutomaticExpensive, "Automatikus módban a runner megáll, mert a kapcsolat korlátos.")
        .Add(LocalizationKeys.PolicyAutomaticExpensiveIgnored, "Automatikus módban a runner futhat, mert a forgalomkorlátos kapcsolat miatti szüneteltetés ki van kapcsolva.")
        .Add(LocalizationKeys.PolicyAutomaticOffline, "Automatikus módban a runner megáll, mert nincs internet.")
        .Add(LocalizationKeys.PolicyAutomaticUnknown, "Automatikus módban a hálózat vizsgálata folyamatban van.")
        .Add(LocalizationKeys.PolicyForceRunning, "Kézi felülbírálattal fut, a hálózati szabály most nem állítja le.")
        .Add(LocalizationKeys.PolicyForceStopped, "Kézi felülbírálattal leállítva marad.")
        .Add(LocalizationKeys.LaunchAtLoginEnabled, "Engedélyezve")
        .Add(LocalizationKeys.LaunchAtLoginRequiresApproval, "Jóváhagyás szükséges")
        .Add(LocalizationKeys.LaunchAtLoginDisabled, "Kikapcsolva")
        .Add(LocalizationKeys.LaunchAtLoginUnavailable, "Ebben a buildben nem érhető el")
        .Add(LocalizationKeys.LaunchAtLoginUnknown, "Ismeretlen")
        .Add(LocalizationKeys.ActivityWorkingJob, "Dolgozik: {0}")
        .Add(LocalizationKeys.ActivityWaitingForJob, "Várakozik feladatra")
        .Add(LocalizationKeys.ActivityStopping, "Leállás folyamatban")
        .Add(LocalizationKeys.ActivityWaitingOrStarting, "Várakozik vagy indul")
        .Add(LocalizationKeys.ActivityRunnerStopped, "A runner le van állítva")
        .Add(LocalizationKeys.ActivityUnknown, "Állapot ismeretlen")
        .Add(LocalizationKeys.NetworkChecking, "Hálózat ellenőrzése...")
        .Add(LocalizationKeys.NetworkNoInternet, "Nincs elérhető internet")
        .Add(LocalizationKeys.NetworkMetered, "{0}, forgalomkorlátos")
        .Add(LocalizationKeys.NetworkUnmetered, "{0}, nem forgalomkorlátos")
        .Add(LocalizationKeys.InterfaceEthernet, "Ethernet")
        .Add(LocalizationKeys.InterfaceWiFi, "Wi-Fi")
        .Add(LocalizationKeys.InterfaceCellular, "Mobilhálózat")
        .Add(LocalizationKeys.InterfaceOther, "Másik kapcsolat")
        .Add(LocalizationKeys.InterfaceGeneric, "Kapcsolat")
        .Add(LocalizationKeys.ErrorMissingRunnerScript, "Nem találom a runner indító scriptet: {0}")
        .Add(LocalizationKeys.ErrorLaunchAtLoginUpdate, "Az automatikus indítás beállítása nem sikerült: {0}")
        .Add(LocalizationKeys.ErrorRunnerHandling, "Nem sikerült a runner kezelése: {0}")
        .Add(LocalizationKeys.SettingsStopOnBatteryTitle, "Runner szüneteltetése akkumulátoron")
        .Add(LocalizationKeys.SettingsStopOnBatteryExplanation, "Automatikusan leállítja a runnert, amikor akkumulátorról fut, és folytatja, amikor áramforrásra van csatlakoztatva.")
        .Add(LocalizationKeys.SettingsStopOnBatteryUnavailable, "Nem érhető el ezen az eszközön")
        .Add(LocalizationKeys.SettingsStopOnMeteredNetworkTitle, "Runner szüneteltetése forgalomkorlátos kapcsolaton")
        .Add(LocalizationKeys.SettingsStopOnMeteredNetworkExplanation, "Automatikusan leállítja a runnert, amikor az aktív internetkapcsolat forgalomkorlátos.");

    private static readonly ImmutableDictionary<string, ImmutableDictionary<string, string>> _catalogs =
        ImmutableDictionary<string, ImmutableDictionary<string, string>>.Empty
            .Add("en", _english)
            .Add("hu", _hungarian);

    private static readonly string[] _supportedLanguageIdentifiers =
    [
        "en", "en-AU", "en-CA", "en-GB", "en-US", "hu"
    ];

    private AppLanguage _currentLanguage = AppLanguage.System;

    public event EventHandler? LanguageChanged;

    public AppLanguage CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            if (_currentLanguage != value)
            {
                _currentLanguage = value;
                LanguageChanged?.Invoke(this, EventArgs.Empty);
            }
        }
    }

    public string Get(string key)
    {
        var catalog = GetActiveCatalog();
        return catalog.TryGetValue(key, out var value) ? value : key;
    }

    public string Get(string key, params object[] args)
    {
        var template = Get(key);
        try
        {
            return string.Format(template, args);
        }
        catch
        {
            return template;
        }
    }

    private ImmutableDictionary<string, string> GetActiveCatalog()
    {
        var identifier = GetActiveLanguageIdentifier();
        return _catalogs.TryGetValue(identifier, out var catalog) ? catalog : _english;
    }

    private string GetActiveLanguageIdentifier()
    {
        if (_currentLanguage == AppLanguage.Hungarian) return "hu";
        if (_currentLanguage == AppLanguage.English) return "en";

        return SystemPreferredLanguageIdentifier();
    }

    private static string SystemPreferredLanguageIdentifier()
    {
        var systemLang = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return _supportedLanguageIdentifiers.Contains(systemLang) ? systemLang : "en";
    }
}
